// Import modules
include { QDNASEQ_CALL         } from '../../../modules/local/qdnaseq/main.nf'         // QDNAseq CNV calling
include { QUARTO_FIGURE        } from '../../../modules/local/quarto/main.nf'          // Quarto figure
include { QUARTO_SECTION       } from '../../../modules/local/quarto/main.nf'          // Quarto section

// Define the main workflow
workflow CNV_CHECK {
    take:
    bam         // channel: from mapping workflow, includes index
    ref         // reference ID (hg19 or hg38)

    main:
    ch_versions = Channel.empty() // For collecting version info

    //Prepare QDNAseq input channel
    ch_in_qdnaseq = bam
        .join(ref)

    // Identify CNV with QDNAseq
    QDNASEQ_CALL (ch_in_qdnaseq)

    /*
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        FIGURE INPUT
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    */

    ch_figure_input = QDNASEQ_CALL.out.cov_png
        .map { meta, figure ->
            def section = "CNV"
            def process = "cnv-qdnaseq-${meta.id}"
            def caption = "Coverage plot for ${meta.id} on BAM files (no filtering)"
            tuple(meta, figure, caption, section, process)
        }
    QUARTO_FIGURE(
        ch_figure_input
    )

    ch_section_inputs = QUARTO_FIGURE.out.quarto_figure

    /*
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        QUARTO_SECTION
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    */

    ch_section_description = channel.value("CNV profiles generated by QDNAseq for each sample. The plots show the normalized read counts across the genome, highlighting regions of copy number gains and losses. Window = " + params.qdnaseq_binsize + "bp.")

    ch_section_inputs = ch_section_inputs
        .map { meta, section, filePaths -> tuple([id: file(params.outdir).name], section, filePaths) }
        .groupTuple()
        .map { meta, section, filePaths -> [meta, section[0], filePaths] }
        .combine(ch_section_description)

    QUARTO_SECTION(
        ch_section_inputs
    )

    ch_section = QUARTO_SECTION.out.quarto_section

    /*
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        COLLECT VERSIONS
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    */

    ch_versions = QDNASEQ_CALL.out.versions
                    .mix(QUARTO_FIGURE.out.versions)
                    .mix(QUARTO_SECTION.out.versions)

    emit:
    qdnaseq_vcf         = QDNASEQ_CALL.out.call_vcf
    qdnaseq_plot        = QDNASEQ_CALL.out.cov_png
    section             = QUARTO_SECTION.out.quarto_section
    versions            = ch_versions

}
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/